## Name: Aryan Mahesh Patil
### Rollno: 46
#### Subject: DL
#### Experiment No: 2

#### Part A: Implement AND Logic Gates using a Perceptron

In [24]:
#!pip install torch

In [2]:
import torch
import torch.nn as nn
import torch.optim as optim

In [3]:
# Input and Output
X = torch.tensor([[0.,0.],
                  [0.,1.],
                  [1.,0.],
                  [1.,1.]])
Y = torch.tensor([[0.],
                  [0.],
                  [0.],
                  [1.]])

In [4]:
# Initialize weights and bias
W = torch.randn(2, 1, requires_grad=True)
b = torch.randn(1, requires_grad=True)
learning_rate = 0.1

In [5]:
# Training
for epoch in range(1000):

    # Forward propagation
    z=X @ W + b
    output = torch.sigmoid(z)

    # Binary Cross Entropy Loss
    # loss = -(Y * torch.log(output) +
    #          (1 - Y) * torch.log(1 - output)).mean()
    criterion = nn.BCELoss()
    loss = criterion(output,Y)

    # Backward propagation computes gradients
    loss.backward()

    # Update weights
    with torch.no_grad():
        W -= learning_rate * W.grad
        b -= learning_rate * b.grad

        W.grad.zero_()
        b.grad.zero_()

In [6]:
# Testing
with torch.no_grad():
    # prediction = (torch.sigmoid(X @ W + b) >= 0.5).float()         #coverts boolean to float
    prediction = (output >= 0.5).float()         #coverts boolean to float

In [7]:
print("Predictions")
print(prediction)

accuracy = (prediction == Y).float().mean() * 100
print("\nAccuracy =", accuracy.item(), "%")

print("\nFinal Weights")
print(W)

print("\nFinal Bias")
print(b)

Predictions
tensor([[0.],
        [0.],
        [0.],
        [1.]])

Accuracy = 100.0 %

Final Weights
tensor([[3.2640],
        [3.2609]], requires_grad=True)

Final Bias
tensor([-5.1044], requires_grad=True)


#### Part B: Solving AND Gate Using NN Library

In [23]:
#!pip install torch

In [9]:
import torch
import torch.nn as nn
import torch.optim as optim

In [10]:
# Input and Output
X = torch.tensor([[0.,0.],
                  [0.,1.],
                  [1.,0.],
                  [1.,1.]])
Y = torch.tensor([[0.],
                  [0.],
                  [0.],
                  [1.]])

In [11]:
# Initialize weights and bias
W = torch.randn(2, 1, requires_grad=True)
b = torch.randn(1, requires_grad=True)
learning_rate = 0.1

In [12]:
model=nn.Sequential(
    nn.Linear(2,1),         # create 2 input 1 output
    nn.Sigmoid()
)

In [13]:
criterion = nn.BCELoss()
optimizer = optim.SGD(model.parameters(),lr=0.1)
for epoch in range(1000):
    output = model(X)
    loss=criterion(output,Y)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

with torch.no_grad():
    prediction=(output>=0.5).float()

print("Prediction")
print(prediction)

Prediction
tensor([[0.],
        [0.],
        [0.],
        [1.]])


In [14]:
print("\nFinal Weights")
print(W)

print("\nFinal Bias")
print(b)


Final Weights
tensor([[-0.7279],
        [ 1.5654]], requires_grad=True)

Final Bias
tensor([-1.5038], requires_grad=True)


### Part C: Implement a Single-Layer Perceptron using PyTorch for Placement Exam

In [15]:
X = torch.tensor([
    [1.,1.],
    [2.,1.],
    [2.,2.],
    [3.,2.],
    [6.,5.],
    [7.,6.],
    [8.,6.],
    [9.,7.]
])

Y = torch.tensor([0.,0.,0.,0.,1.,1.,1.,1.]).view(-1,1)

In [16]:
weights = torch.zeros(2)
bias = torch.tensor(0.)

In [17]:
# Method 1: Manual Implementation
# Training
for epoch in range(1000):

    # Forward propagation
    z=X @ W + b
    output = torch.sigmoid(z)

    criterion = nn.BCELoss()
    loss = criterion(output,Y)

    # Backward propagation computes gradients
    loss.backward()

    # Update weights
    with torch.no_grad():
        W -= learning_rate * W.grad
        b -= learning_rate * b.grad

        W.grad.zero_()
        b.grad.zero_()

In [18]:
# Testing
with torch.no_grad():
    # prediction = (torch.sigmoid(X @ W + b) >= 0.5).float()         #coverts boolean to float
    prediction = (output >= 0.5).float()         #coverts boolean to float

In [19]:
print("Predictions")
print(prediction)

accuracy = (prediction == Y).float().mean() * 100
print("\nAccuracy =", accuracy.item(), "%")

print("\nFinal Weights")
print(W)

print("\nFinal Bias")
print(b)

Predictions
tensor([[0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.]])

Accuracy = 100.0 %

Final Weights
tensor([[-0.2185],
        [ 1.9572]], requires_grad=True)

Final Bias
tensor([-5.6413], requires_grad=True)


In [20]:
# Method 2: Using Stochastic Gradient Descent
model=nn.Sequential(
    nn.Linear(2,1),         # create 2 input 1 output
    nn.Sigmoid()
)

In [21]:
criterion = nn.BCELoss()
optimizer = optim.SGD(model.parameters(),lr=0.1)
for epoch in range(1000):
    output = model(X)
    loss=criterion(output,Y)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

with torch.no_grad():
    prediction=(output>=0.5).float()

print("Prediction")
print(prediction)

Prediction
tensor([[0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.]])


In [22]:
print("\nFinal Weights")
print(W)

print("\nFinal Bias")
print(b)


Final Weights
tensor([[-0.2185],
        [ 1.9572]], requires_grad=True)

Final Bias
tensor([-5.6413], requires_grad=True)
