In [6]:
#!pip install torch

In [11]:
import torch
import torch.nn as nn
import torch.optim as optim

In [12]:
# Input and Output
X = torch.tensor([[0.,0.],
                  [0.,1.],
                  [1.,0.],
                  [1.,1.]])
Y = torch.tensor([[0.],
                  [0.],
                  [0.],
                  [1.]])

In [13]:
# Initialize weights and bias
W = torch.randn(2, 1, requires_grad=True)
b = torch.randn(1, requires_grad=True)
learning_rate = 0.1

In [15]:
model=nn.Sequential(
    nn.Linear(2,1),
    nn.Sigmoid()
)

In [17]:
criterion=nn.BCELoss()
optimizer=optim.SGD(model.parameters(),lr=0.1)
for epoch in range(1000):
    output=model(X)
    loss=criterion(output, Y)
    
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

with torch.no_grad():
    prediction=(output>=0.5).float()

print("Predictions")
print(prediction)

Predictions
tensor([[0.],
        [0.],
        [0.],
        [1.]])


In [18]:
print("\nFinal Weights")
print(W)

print("\nFinal Bias")
print(b)


Final Weights
tensor([[3.0581],
        [3.0359]], requires_grad=True)

Final Bias
tensor([-4.7875], requires_grad=True)
